apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: acme-orders
  template:
    metadata:
      labels:
        app: acme-orders
    spec:
      containers:
        - name: acme-orders
          image: acme-orders:demo
          ports:
            - containerPort: 3000
          securityContext:
            privileged: true
            runAsUser: 0
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: acme-orders
spec:
  selector:
    app: acme-orders
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer